services:
  metamodels.attribute_geodistance.factory:
    class: MetaModels\AttributeGeoDistanceBundle\Attribute\AttributeTypeFactory
    arguments:
      - "@database_connection"
      - "@metamodels.table_manipulator"
      - "@contao.framework"
    tags:
      - { name: metamodels.attribute_factory }
