services:
    metamodels.attribute_text.factory:
        class: MetaModels\AttributeGeoDistanceBundle\Attribute\AttributeTypeFactory
        arguments:
            - "@database_connection"
            - "@metamodels.table_manipulator"
        tags:
          - { name: metamodels.attribute_factory }
